#  DON'T EDIT THIS FILE.
#  THIS IS GENERATED BY "Configuration/configure_BuildRule.py".


OBJECTS = \
$(OUTDIR)\.\Viewer\BufferObject.obj \
$(OUTDIR)\.\Viewer\FragmentShader.obj \
$(OUTDIR)\.\Viewer\FrameBufferObject.obj \
$(OUTDIR)\.\Viewer\GeometryShader.obj \
$(OUTDIR)\.\Viewer\IndexBufferObject.obj \
$(OUTDIR)\.\Viewer\PixelBufferObject.obj \
$(OUTDIR)\.\Viewer\ProgramObject.obj \
$(OUTDIR)\.\Viewer\RenderBuffer.obj \
$(OUTDIR)\.\Viewer\ShaderObject.obj \
$(OUTDIR)\.\Viewer\ShaderSource.obj \
$(OUTDIR)\.\Viewer\Texture3D.obj \
$(OUTDIR)\.\Viewer\VertexBufferObject.obj \
$(OUTDIR)\.\Viewer\VertexShader.obj \



{.\Viewer\}.cpp{$(OUTDIR)\.\Viewer\}.obj::
	IF NOT EXIST $(OUTDIR)\.\Viewer $(MKDIR) $(OUTDIR)\.\Viewer
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\Viewer\ @<<
$<
<<


install::
	IF NOT EXIST $(INSTALL_DIR)\include\SupportGLEW\. $(MKDIR) $(INSTALL_DIR)\include\SupportGLEW\.
	$(INSTALL) .\*.h $(INSTALL_DIR)\include\SupportGLEW\.
	IF NOT EXIST $(INSTALL_DIR)\include\SupportGLEW\.\Viewer $(MKDIR) $(INSTALL_DIR)\include\SupportGLEW\.\Viewer
	$(INSTALL) .\Viewer\*.h $(INSTALL_DIR)\include\SupportGLEW\.\Viewer
