/* DON'T EDIT THIS FILE.
 * THIS IS GENERATED BY "shader2header.c".
 */
#ifndef KVS__GLEW__GLSL__Shader_H_INCLUDE
#define KVS__GLEW__GLSL__Shader_H_INCLUDE

namespace kvs
{

namespace glew
{

namespace glsl
{

namespace Shader
{

namespace Vertex
{

const char* phong =
    "varying vec3 position;\n"
    "varying vec3 normal;\n"
    "\n"
    "void main( void )\n"
    "{\n"
    "    gl_FrontColor = gl_Color;\n"
    "    gl_Position = ftransform();\n"
    "\n"
    "    position = vec3( gl_ModelViewMatrix * gl_Vertex );\n"
    "    normal = gl_NormalMatrix * gl_Normal.xyz;\n"
    "}\n"
;

} // end of namespace Vertex

namespace Fragment
{

const char* phong =
    "struct Shader\n"
    "{\n"
    "    float Ka; // ambient\n"
    "    float Kd; // diffuse\n"
    "    float Ks; // specular\n"
    "    float S;  // shininess\n"
    "};\n"
    "\n"
    "varying vec3 position;\n"
    "varying vec3 normal;\n"
    "\n"
    "uniform Shader shader;\n"
    "\n"
    "\n"
    "float lambertShading( in vec3 L, in vec3 N )\n"
    "{\n"
    "    float dd = max( dot( N, L ), 0.0 );\n"
    "\n"
    "    float Ia = shader.Ka;\n"
    "    float Id = shader.Kd * dd;\n"
    "\n"
    "    return( Ia + Id );\n"
    "}\n"
    "\n"
    "float phongShading( in vec3 L, in vec3 N )\n"
    "{\n"
    "    vec3 R = 2.0 * dot( N, L ) * N - L;\n"
    "    float dd = max( dot( N, L ), 0.0 );\n"
    "    float ds = pow( max( dot( N, R ), 0.0 ), shader.S );\n"
    "\n"
    "    float Ia = shader.Ka;\n"
    "    float Id = shader.Kd * dd;\n"
    "    float Is = shader.Ks * ds;\n"
    "\n"
    "    return( Ia + Id + Is );\n"
    "}\n"
    "\n"
    "float blinnPhongShading( in vec3 L, in vec3 N, in vec3 C )\n"
    "{\n"
    "    vec3 H = normalize( L + C );\n"
    "    float dd = max( dot( N, L ), 0.0 );\n"
    "    float ds = pow( max( dot( H, N ), 0.0 ), shader.S );\n"
    "\n"
    "    float Ia = shader.Ka;\n"
    "    float Id = shader.Kd * dd;\n"
    "    float Is = shader.Ks * ds;\n"
    "\n"
    "    return( Ia + Id + Is );\n"
    "}\n"
    "\n"
    "void main( void )\n"
    "{\n"
    "    vec3 L = normalize( gl_LightSource[0].position.xyz - position );\n"
    "    vec3 N = normalize( normal );\n"
    "\n"
    "#if   defined( ENABLE_LAMBERT_SHADING )\n"
    "    float attenuate = lambertShading( L, N );\n"
    "#elif defined( ENABLE_PHONG_SHADING )\n"
    "    float attenuate = phongShading( L, N );\n"
    "#elif defined( ENABLE_BLINN_PHONG_SHADING )\n"
    "    vec3 C = normalize( position );\n"
    "    float attenuate = phongShading( L, N, C );\n"
    "#else // NO SHADING\n"
    "    float attenuate = 1.0;\n"
    "#endif\n"
    "\n"
    "    gl_FragColor.xyz = gl_Color.xyz * attenuate;\n"
    "    gl_FragColor.w = 1.0;\n"
    "}\n"
;

} // end of namespace Fragment

} // end of namespace Shader

} // end of namespace glsl

} // end of namesapce glew

} // end of namespace kvs

#endif // KVS__GLEW__GLSL__Shader_H_INCLUDE
