#  DON'T EDIT THIS FILE.
#  THIS IS GENERATED BY "Configuration/configure_BuildRule.py".


OBJECTS = \
$(OUTDIR)\.\DriverAPI\Context.obj \
$(OUTDIR)\.\DriverAPI\Device.obj \



{.\DriverAPI\}.cpp{$(OUTDIR)\.\DriverAPI\}.obj::
	IF NOT EXIST $(OUTDIR)\.\DriverAPI $(MKDIR) $(OUTDIR)\.\DriverAPI
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\DriverAPI\ @<<
$<
<<


install::
	IF NOT EXIST $(INSTALL_DIR)\include\SupportCUDA\. $(MKDIR) $(INSTALL_DIR)\include\SupportCUDA\.
	$(INSTALL) .\*.h $(INSTALL_DIR)\include\SupportCUDA\.
	IF NOT EXIST $(INSTALL_DIR)\include\SupportCUDA\.\DriverAPI $(MKDIR) $(INSTALL_DIR)\include\SupportCUDA\.\DriverAPI
	$(INSTALL) .\DriverAPI\*.h $(INSTALL_DIR)\include\SupportCUDA\.\DriverAPI
